[default]

[default.db]
uri = ""
connect_args = {check_same_thread=false}
echo = false


[default.security]
# Set secret key in .secrets.toml
SECRET_KEY = "troque_por_favor_no_secrets_toml"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
REFRESH_TOKEN_EXPIRE_MINUTES = 600
